#!/bin/sh

export APERIOLIVE=aplive
mkdir ./$APERIOLIVE

sudo debootstrap \
	--arch=amd64 \
	--variant=minbase \
	stable ./$APERIOLIVE/chroot \
	http://deb.debian.org/debian

sudo cp ./apchroot ./$APERIOLIVE/chroot/bin/apchroot
sudo cp ./apinstall ./$APERIOLIVE/chroot/bin/apinstall
sudo cp ./apupdate ./$APERIOLIVE/chroot/bin/apupdate

sudo chroot ./$APERIOLIVE/chroot
