#!/bin/sh

export APERIOLIVE=aplive

grub-mkstandalone \
	--format=x86_64-efi \
	--output=./$APERIOLIVE/aproot/bootx64.efi \
	--locales="" \
	--fonts="" \
	"boot/grub/grub.cfg=$APERIOLIVE/aproot/grub.cfg"

(cd ./$APERIOLIVE/aproot && \
	dd if=/dev/zero of=efiboot.img bs=1M count=10 && \
	mkfs.vfat efiboot.img && \
	mmd -i efiboot.img efi efi/boot && \
	mcopy -i efiboot.img ./bootx64.efi ::efi/boot/
)

grub-mkstandalone \
	--format=i386-pc \
	--output=./$APERIOLIVE/aproot/core.img \
	--install-modules="linux normal iso9660 biosdisk memdisk search tar ls" \
	--modules="linux normal iso9660 biosdisk search" \
	--locales="" \
	--fonts="" \
	"boot/grub/grub.cfg=./$APERIOLIVE/aproot/grub.cfg"

cat \
	/usr/lib/grub/i386-pc/cdboot.img \
	./$APERIOLIVE/aproot/core.img \
> ./$APERIOLIVE/aproot/bios.img

xorriso \
	-as mkisofs \
	-iso-level 3 \
	-full-iso9660-filenames \
	-volid "APERIOLIVE" \
	-eltorito-boot \
		boot/grub/bios.img \
		-no-emul-boot \
		-boot-load-size 4 \
		-boot-info-table \
		--eltorito-catalog boot/grub/boot.cat \
	--grub2-boot-info \
	--grub2-mbr /usr/lib/grub/i386-pc/boot_hybrid.img \
	-eltorito-alt-boot \
		-e EFI/efiboot.img \
		-no-emul-boot \
	-append_partition 2 0xef ./$APERIOLIVE/aproot/efiboot.img \
	-output "./$APERIOLIVE/APERIO-LIVECD.iso" \
	-graft-points \
  	"./$APERIOLIVE/image" \
  	/boot/grub/bios.img=./$APERIOLIVE/aproot/bios.img \
  	/EFI/efiboot.img=./$APERIOLIVE/aproot/efiboot.img

ls -lh ./$APERIOLIVE/*.iso
